<?php

namespace Bordeux\Bundle\GeoNameBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
	public static function italyCountryQueryBuilder(CountryRepository $r): QueryBuilder
	{
	    return $r->createQueryBuilder('e')
	       ->where('e.id = :country_id')
	       ->setParameter('country_id', 3175395)
	       ->orderBy('e.name', 'DESC');
	 }
}
